config/routes.rb
Radibloga::Application.routes.draw do
    devise_for :users
    namespace :manage do
      resources :accounts
      
      match 'blogs' => 'blogs#index', :via => :get, :as => 'blog'
      match 'blogs/import' => 'blogs#import', :via => :post, :as => 'import'
      
      match 'post/add/:id' => 'blogs#add_post', :as => 'add_imported_post'
      match 'post/unlock/:id' => 'blogs#unlock_add_post', :as => 'unlock_imported_post'
      
      match 'posts' => 'posts#index', :as => 'posts'
      match 'posts/:id' => 'posts#show', :as => 'post'
      match 'posts/comment/:id' => 'posts#close', :via => :delete, :as => 'close_comment'
    end
    
    root :to => 'home#index'
    match '/post/:id' => 'home#show', :via => :get, :as => 'show_post'
    match '/post/:id' => 'home#create', :via => :post, :as => 'post_comment'
    # match 'comment' => 'testcomment#index', :via => :get, :as => 'add_comment'
    # match 'comment' => 'testcomment#submit', :via => :post
    
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
  has_many :comments
end

app/models/resume.rb
class Resume < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user
  has_many :posts
  validates :login, :password, :presence => true
  validates :password, :length => { :in => 6..30 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :resume
  has_many :services
  has_many :posts
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :encryptable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  layout 'account'
  before_filter :authenticate_user!
  
  def new
    @service = Service.new
  end

  def create
    @service = Service.new(params[:service])
    if @service.save
      current_user.services << @service
      redirect_to account_path
    else
      render :new
    end
  end
  
  def show
    @services = current_user.services
  end
  
  def delete
    Service.delete(params[:id])
    redirect_to account_path
  end
  
  def edit
    @service = Service.find(params[:id])
  end
  
  def update
    @service = Service.find(params[:id])
    
    if @service.update_attributes(:login => params[:login], :password => params[:password])
      redirect_to account_path
    else
      render :edit
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActionController::RoutingError, :with => :render_404
  
  protect_from_forgery
  private
  def render_404(exception = nil)
    render :template => 'errors/404', :status => 404
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!
  
  def show
    @accounts = current_user.services
  end

  def import
    account = Service.find(params[:account])
    user = LJAPI::User.new(account.login, account.password)
    begin
      @posts = LJAPI::Request::GetPosts.new(user).run
    rescue LJAPI::Request::LJException => e
      flash[:error] = e.message
      redirect_to import_account_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.limit(10).order('ID DESC')
  end
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments if @post.comments
    @accounts = current_user.services if current_user
    @comment = Comment.new
  end
  
  def create
    @post = Post.find(params[:id])
    service = Service.find(params[:account])

    begin 
      user = LJAPI::User.new(service.login,service.password)
      @ljc = LJAPI::Request::AddComment.new(user, @post.post_id, @post.anum, params[:text].to_s).run
    rescue LJAPI::Request::LJException => e
      flash[:error] = t('ljapi.error.%s' % e.code)
      redirect_to show_post_path(@post)
    end
    @comment = Comment.new(:user => current_user.email, :text => params[:text], :url => @ljc)
    @post.comments << @comment
    redirect_to show_post_path(@post)
  end
end

app/controllers/testcomment_controller.rb
require 'xmlrpc/client'

class TestcommentController < ApplicationController
  before_filter :authenticate_user!
  rescue_from Exception do |exc|
    render 'testcomment/error', :locals => { :error => exc }
  end
  
  def submit
    login = params[:login]
    password = params[:password]
    journal = /\/\/(\w*).*\/(\d*)/.match(params[:link])[1]
    pid = /\/\/(\w*).*\/(\d*)/.match(params[:link])[2]
    subject = ERB::Util.html_escape(params[:subject])
    body = ERB::Util.html_escape(params[:body])
    
    connection = XMLRPC::Client.new('www.livejournal.com', '/interface/xmlrpc')
    
    request = {
      'clientversion' => 'Ruby',
      'ver' => 1,
      'journal' => journal,
      'ditemid' => pid,
      'username' => login,
      'password' => password,
      'subject' => subject,
      'body' => body
    }
    
    response = connection.call('LJ.XMLRPC.addcomment',request)
    
    if response['status'] != 'OK'
      render 'testcomment/error'
    else 
      redirect_to response['commentlink']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def notifications_display
    form = []
    flash.each do |k,m|
      form << content_tag(:div, content_tag(:p, m.to_s), :id => "#{k}_notice", :class => "#{k} message")
    end
    raw(form.flatten.map { |e| e.mb_chars }.join())
  end
  
  def authentication_error
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:div, content_tag(:strong, t('error')) + msg, :class => 'warning message') }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML 
      <h2>#{sentence}</h2>
      #{messages}
    HTML

    html.html_safe
  end
  
  def form_errors(record)
    tag = []
    record.errors.full_messages.each { |m| tag << content_tag(:div, content_tag(:p, m.to_s), :class => "error message") }
    raw(tag.flatten.map { |e| e.mb_chars }.join())
  end
end

app/views/authentication/_login_form.html.erb
<div class="auth_header">
	<%= content_tag(:h3, t('login')) %>
	<ul>
		<li><%= link_to "Зарегистрироваться",'#', :id => 'register_link' %></li>
		<li>Восстановить пароль</li>
	</ul>
</div>
<div class="auth_content">
	<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
	<fieldset>
	<dl>
		<dt><%= f.label :email %></dt>
		<dd><%= f.email_field :email %></dd>
	
		<dt><%= f.label :password %></dt>
		<dd><%= f.password_field :password %></dd>
	</dl>
	</fieldset>
	<div class="submit">
		<%= f.submit "Войти" %>
	</div>
	<div class="remember">
		<%= f.check_box :remember_me %> <%= f.label :remember_me, 'запомнить' %>
	</div>
	<% end %>
</div>

app/views/authentication/_signup_form.html.erb
<div class="auth_header">
	<%= content_tag(:h3, t('signup')) %>
</div>
<div class="auth_content">
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
	<fieldset>
		<dl>
			<dt><%= f.label :email %></dd>
			<dd><%= f.email_field :email %></dd>
			
			<dt><%= f.label :password %></dd>
			<dd><%= f.password_field :password %></dd>
			
			<dt><%= f.label :password_confirmation %></dd>
			<dd><%= f.password_field :password_confirmation %></dd>
		</dl>
	</fieldset>
	<div class="submit">
  		<%= f.submit "Регистрация" %>
	</div>
<% end %>
</div>

app/views/home/_comment.html.erb
<%= content_tag(:b, comment.user) %>
	<%= content_tag :p do %>
		<%= content_tag :b, comment.created_at %>
		<%= content_tag :p, comment.text %>
		<%= content_tag :strong, link_to(t('url'), comment.url) %>
	<% end %>
<hr>

app/views/home/_comment_form.html.erb
<%= form_for @comment, :url => post_comment_url(@post) do %>

	<%= label_tag :account, t('manage.posts.choose_account')%>
	<%= select_tag 'account', options_from_collection_for_select(@accounts, 'id', 'login') %>
	
	<%= label_tag :comment, t('manage.posts.comment_text')%>
	<%= text_area_tag :text %>
	<%= submit_tag t('send') %>
<% end %>

app/views/home/_post.html.erb
<h2><%= link_to (post.subject or post.id), show_post_path(post.id) %></h2>
<BR>
<%= content_tag(:p, truncate(post.text)) %>
<hr>

app/views/home/index.html.erb
<h1><%= t('latest_posts') %></h1>

<%= render :partial => 'post', :collection => @posts %>

app/views/home/show.html.erb
<%= content_tag(:h1, (@post.subject or @post.id))%>

<%= content_tag(:p, @post.text) %>

<hr>
<% if @comments.any? %>
	<%= render :partial => 'comment', :collection => @comments %>
<% end %>
<% if current_user %>
	<%= render :partial => 'comment_form' %>
<% end %>

app/views/layouts/account.html.erb
<%= render :template => 'layouts/application' %>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>.Radi/bloga</title>
  <meta name="description" content="Radibloga">
  <meta name="author" content="7q">
  <meta name="viewport" content="width=device-width,initial-scale=1">  
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div class="backlayer_top"></div>
	<div class="backlayer_rest"></div>
	<div class="container_12">
		<div class="grid_12 heading">
			4Blog
		</div>
		<div class="clear"></div>
		<div class="grid_12 menu">
			<div class="grid_10 menu_left alpha">
				<%= render :partial => 'partial/menu' %>
			</div>
		</div>
		<div class="clear"></div>
		<div class="grid_8 content">
			<%= render :partial => 'partial/notice' %>
			<%= yield %>
		</div>
		<div class="grid_3 sidebar">
			<%= content_for?(:sidebar) ? yield(:sidebar) : render(:partial => 'partial/sidebar') %>
			<BR>
			<span class="version">version: <%= APP_VERSION %></span>
		</div>
		<div class="clear"></div>
	</div>
</body>
</html>

app/views/partial/_menu.html.erb
<%= link_to t('home'), :root %> | 
<% if user_signed_in? %>
	<%= link_to current_user.email, manage_accounts_path %> - <%= link_to t('logout'), destroy_user_session_path, :method => :delete %>
<% else %>
	<%= link_to t('account'), new_user_session_path %>
<% end %>

app/views/partial/_notice.html.erb
<%= notifications_display %>

app/views/partial/_sidebar.html.erb
<nav>
	<h3><%= t('manage.accounts.title') %></h3>
	<li><%= link_to t('manage.accounts.link'), manage_accounts_path %></li>
	<li><%= link_to t('manage.accounts.add'), new_manage_account_path %></li>
	<h3><%= t('manage.blogs.title') %></h3>
	<li><%= link_to t('manage.blogs.import_title'), manage_blog_path %></li>
	<h3><%= t('manage.posts.title') %></h3>
	<li><%= link_to t('manage.posts.link'), manage_posts_path %></li>
</nav>

app/views/testcomment/error.html.erb
<h2>Ошибка при добавлении комментария</h2>

При добавлении комментария произошла ошибка.
<br>
<div><%= error.message %></div>

app/views/testcomment/index.html.erb
<h1>Add commentary</h1>
<div class="comment_form">
<%= form_tag('/comment', :method => :post) do %>
	<%= label_tag 'Link to post:' %>
	<%= text_field_tag 'link', nil, :placeholder => 'Enter link to LJ post' %>
	<%= label_tag 'LJ Login' %>
	<%= text_field_tag 'login', nil, :placeholder => 'LJ Login' %>
	<%= label_tag 'LJ Password' %>
	<%= text_field_tag 'password', nil, :placeholder => 'LJ Password' %>
	<%= label_tag 'Comment subject' %>
	<%= text_field_tag 'subject', nil, :placeholder => 'Subject text' %>
	<%= label_tag 'Comment text' %>
	<%= text_area_tag 'body', nil, :size => "45x10" %>
	
	<%= submit_tag 'Send' %>
<% end %>
</div>
<% content_for(:sidebar) do %>
	<%= link_to 'Add commentary', add_comment_path %>
<% end %>